### ISSUE TITLE
Update README with instructions on Nakama Include Paths

### ISSUE THREAD

**Issue by spentak** [heroiclabs/nakama-unreal#17] opened 2019-07-07 03:57 UTC
Following the steps in the README will allow the project to compile and work, but Visual Studio/Other IDEs show errors for includes on "nakama-cpp"

I suggest updating the README with the following:

For Nakama to operate correctly within Intellisense on any modern IDE you will want to add the public include paths for the plugin in your project's `.Build.cs` file.

Your code in `.Build.cs` might look like this:

```
using UnrealBuildTool;
using System.IO;

public class YourProjectName : ModuleRules
{
	public YourProjectName(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
	
		PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore" });

		PrivateDependencyModuleNames.AddRange(new string[] { "Nakama" });

        var basePath = Path.GetDirectoryName(RulesCompiler.GetFileNameFromType(GetType()));
        string pluginsPath = Path.Combine(basePath, "..","..", "Plugins");
        PublicIncludePaths.Add(Path.Combine(pluginsPath, "Nakama", "Source", "Nakama", "Public", "nakama-cpp"));
	}
}
```

**Comment by Dimon4eg** [comment] 2019-07-08 18:38
I don't know why have problems with IDEs.
It works fine for me:
![image](https://user-images.githubusercontent.com/1271541/60834115-93665880-a1c8-11e9-9ae0-84078f70821d.png)
I use VS 2017 and UE 4.22.

In which IDE do you have problem?
Which UE?

**Comment by spentak** [comment] 2019-07-09 03:01
VS 2019 UE 4.22

**Comment by Dimon4eg** [comment] 2019-10-28 07:03
Cannot reproduce in VS 2019 and UE 4.23.
Nakama module exports include directories, you don't need to do that manually.
Closing the issue.

**Closed by Dimon4eg** 2019-10-28 07:03 UTC
